### ISSUE TITLE
Handle when there are 0 transactions

### ISSUE THREAD

**Issue by liamzebedee** [ascribe/transactions#70]
I'm getting this error when trying to build a simple_transaction and the address returns 0 transactions. Was a bit confusing initially:

```
File "/usr/local/lib/python2.7/site-packages/transactions/services/blockrservice.py", line 50, in list_transactions
    for tx in results['txs']:
TypeError: list indices must be integers, not unicode
```

When the response data looks like this:

```
[{u'txs': [], u'limit_txs': 200, u'nb_txs': 0, u'nb_txs_displayed': 0, u'address': u"(u''"}, {u'txs': [], u'limit_txs': 200, u'nb_txs': 0, u'nb_txs_displayed': 0, u'address': u" u'1Lo9DHhZZsoZJdyVrkcTot3Ha6mjNcmgw7')"}]
```

**Comment by sbellem** [comment]
I assume the [signature of `simple_transaction`](https://transactions.readthedocs.io/en/latest/code.html#transactions.Transactions.simple_transaction) or its alias `create` is confusing. This is a good reason to improve it.

It looks like you are passing a tuple for the `from_address` parameter. For example, the following works:

```python
from transactions import Transactions
alice = 'mhyCaF2HFk7CVwKmyQ8TahgVdjnHSr1pTv'
bob = 'mqXz83H4LCxjf2ie8hYNsTRByvtfV43Pa7'
transactions = Transactions(testnet=True)
tx = transactions.create(alice, (bob, 10000))
```
but the following:

```python
tx = transactions.create(('', alice), (bob, 10000))
```
will yield the error:
```python
TypeError: list indices must be integers, not unicode
```
because the code is expecting a `dict`, but it got a list, and tried to retrieve the value `'txs'` from the list:

```python
[{u'address': u"(''",
  u'limit_txs': 200,
  u'nb_txs': 0,
  u'nb_txs_displayed': 0,
  u'txs': []},
 {u'address': u" 'mhyCaF2HFk7CVwKmyQ8TahgVdjnHSr1pTv')",
  u'limit_txs': 200,
  u'nb_txs': 0,
  u'nb_txs_displayed': 0,
  u'txs': []}]
```

**Comment by liamzebedee** [comment]
Haha figured this out too! :) thanks.

**Comment by sbellem** [comment]
Ok! WIll close the ticket then.
